### ISSUE TITLE
For Cycle 8

### ISSUE THREAD

**Issue by rex4539** [bisq-network/compensation#417]
## Summary

> _Specify the total amount of BSQ you are requesting:_

 - BSQ requested: 2070

## Contributions delivered

> _Provide links to contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19), the amount of BSQ you are requesting for each, and any comments that will help stakeholders understand its value._

https://github.com/bisq-network/bisq/pull/3643 (162 fixes in 87 files)
https://github.com/bisq-network/bisq/pull/3647 (14 fixes in 10 files)
https://github.com/bisq-network/bisq/pull/3659 (8 fixes in 1 file)
https://github.com/bisq-network/bisq/pull/3637 (8 fixes in 5 files)
https://github.com/bisq-network/incubator-bisq-xmr-integration/pull/2 (9 fixes in 6 files)
https://github.com/bisq-network/bisq-docs/pull/179 (4 fixes in 2 files)
https://github.com/bisq-network/bisq-website/pull/289 (2 fixes in 2 files)

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional,** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

https://github.com/bisq-network/incubator-bisq-api/pull/21 (pending merge)

**Comment by julianknutsen** [comment]
At first glance, this seems very high given the impact and user-value of the changes. Can you explain a bit more about the work involved and how to think about this from a DAO voter's point of view?

**Comment by chimp1984** [comment]
Agree. Even most typos fixes have been in comments (at least here https://github.com/bisq-network/bisq/pull/3643/commits/587b55d37bb04a943b55642eba0b19f1e3b05d46). All nice to have but 4820 BSQ is way too high IMO.

**Comment by rex4539** [comment]
Good morning, gentlemen.

You are absolutely right. I somehow made the wrong calculation.

I was supposed to use the exact logic as in https://github.com/bisq-network/compensation/issues/78, https://github.com/bisq-network/compensation/issues/106, https://github.com/bisq-network/compensation/issues/167

Basically, 10 BSQ per fix.

I have fixed the amount requested.

I have no recollection how the 4820 number came to be (sounds absurd to me too!) and thanks for pointing it out :)

**Comment by julianknutsen** [comment]
Thanks for pointing out the prior requests that were accepted with this amount.

I can understand the need for user-facing documents to be edited like this. Having fewer typos and grammar mistakes gives off a more confident tone and may encourage more users to try out the software.

But as a newcomer here, it still isn't clear to me why the project needs to sustain a 10 BSQ inflation for every comment that doesn't have perfect grammar or capitalization. This project will always have contributors that may not have English as their first language and it isn't productive to have code reviewers double-checking and polluting reviews with grammar checks.

How should a DAO voter look at this type of work in the broader scope of user-value and decide that this is something that should be funded?

If this is important, how expensive would it be to just automate the grammar checking every month and obviate this type of manual work?

Lastly, as a nit, I'm not 100% sure the incubator projects are still funded so contributions to those repositories seem even less valuable.

This is my first cycle with the project so these questions may seem a bit different than previous iterations. I'm trying to get caught up with how __*delivery*__ and __*value*__ fit in with different types of requests.

Happy to hear your thoughts. Thanks.

**Comment by trigger67** [comment]
For the translations the rates are: 0.07BSQ per word. For the review it is 0.035BSQ per word.

As I can see you request 10BSQ for fixing a typo, so it is equivalent to translating 142 words in a foreign language...

I agree fixing typos is good, but the rate seems way too high for me, at least 10 times.
Maybe 10 BSQ for one commit with one typo seems OK. But 1620 BSQ for one small commit fixing 162 typos seems tremendous for me.

I am new here and just started to look at compensation requests, just trying to help finding a fair rate :)

**Comment by chimp1984** [comment]
I agree with @trigger67 this still seems very high. 

I would like to kick of a discussion around that topic.
There are currently quite a lot of compensation requests in the translations area which sums up to about 10 000 BSQ from a rough overview. 
I appreciate the progress and recognize the importance of translations but I have the feeling that the costs are not proportional to the added value. We should see translation work in the perspective of markets growth and define the goals and the expenses we are willing to spend for reaching those goals. 
I do not follow much the translations area so please apologize if I missed something important. But I think we should try to get a discussion to bring different "departments" under a strategic umrella. Something like "business development" in traditional companies might be needed to coordinate and adjust efforts in different areas and to meassure costs and benefits. Not sure if anyone is in charge of that already, I think @arunasurya, @flix1 and @m52go might be the people who have the best overview here. Maybe you could comment? 

At the moment trade volume is very low and with that burned BSQ. I think in such times we should be more conservative with expenses to not inflate the BSQ value too much. That does not mean that we should not invest in important work which helps us to increase trade volume, but I do not see clearly how the roughly 10 000 BSQ which is currently visible for requests will translate into trade volume growth which justifies those costs.

**Comment by m52go** [comment]
> this still seems very high.

Yes, drastically. As noted above, the biggest item here is https://github.com/bisq-network/bisq/pull/3643, which seems like mostly code comments to me. In my opinion this is the least valuable form of correction. The rest are relatively small, combined. I'm not sure why the previous typo compensation requests from rex4539 were accepted at 10 BSQ/typo, but I'm surprised they were.

> But I think we should try to get a discussion to bring different "departments" under a strategic umrella.

There is no coordinated effort but we're trying to do something of the sort. arunasurya is working on determining criteria for adding languages, and @julianknutsen [started discussion](https://github.com/bisq-network/proposals/issues/150) on tracking expenses after each cycle to evaluate return on investment. 

I tend to encourage and discourage efforts across my own domains (website, docs, growth) based on a loose sense of how well the project is going. At this point, I'm not sure it makes sense to create another position for coordinating these activities. I think it's sufficient for the main "managers" in each area to have periodical discussions to determine how much leeway there is for less-critical items, and then merge accordingly (growth, translations, documentation, website, etc).

This case is a bit strange because it doesn't really fall under the purview of any particular function, so I'm not sure any amount of coordination would have helped...but fixing typos shouldn't ever be this big of a line-item either.

**Comment by arunasurya** [comment]
I am open to discussing this further. Perhaps we can start by determining how much major projects cost, what fraction of the total cost they are, and set aside a certain budget for projects depending on their usefulness, which can be adjusted whenever demand for it changes. 

For the Transifex project, the costs are compensation requests for translators and admins which I can start keeping track of monthly. We are also planning to track YouTube views and site visits in different languages to determine how useful the other two projects (website and subtitles) are. I think maybe it is a good idea to have the bare minimum budget for basic translation and admin work that can be available at all times and then set aside resources for expanding into new markets when we have more revenue. 

I am open to more discussions on this topic.

**Comment by m52go** [comment]
The whole project needs some kind of mechanism for establishing and tracking budgeting and priorities. I should have a proposal out before the end of the week.

**Comment by MwithM** [comment]
Compensation was rejected by DAO. Kept open a few days for discussion.

**Comment by MwithM** [comment]
Closed as rejected.
